[tool.poetry]
name = "advent2025"
version = "0.1.0"
description = ""
authors = ["kmisiarz <kmisiarz@UGent.be>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<4.0"
numpy = "^2.3.5"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
